In [3]:
# AI Investment Opportunity Analyzer
# Notebook 01: Synthetic Data Generation

import pandas as pd
import numpy as np
from pathlib import Path

# Reproducibility
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

# Project paths
PROJECT_ROOT = Path.cwd().parent
RAW_DATA_PATH = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA_PATH = PROJECT_ROOT / "data" / "processed"

RAW_DATA_PATH.mkdir(parents=True, exist_ok=True)
PROCESSED_DATA_PATH.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Raw data path:", RAW_DATA_PATH)
print("Processed data path:", PROCESSED_DATA_PATH)

Project root: d:\Senior last\ML\ai-investment-opportunity-analyzer
Raw data path: d:\Senior last\ML\ai-investment-opportunity-analyzer\data\raw
Processed data path: d:\Senior last\ML\ai-investment-opportunity-analyzer\data\processed

In [4]:
# Dataset configuration

N_SAMPLES = 5000

sectors = [
    "Real Estate",
    "Tourism",
    "Entertainment",
    "Healthcare",
    "Logistics",
    "Renewable Energy",
    "Technology",
    "Education",
    "Retail",
    "Infrastructure"
]

regions = [
    "Riyadh",
    "Makkah",
    "Madinah",
    "Eastern Province",
    "Qassim",
    "Asir",
    "Tabuk",
    "Jazan"
]

competition_levels = [
    "Low",
    "Medium",
    "High"
]

print("Number of samples:", N_SAMPLES)
print("Number of sectors:", len(sectors))
print("Number of regions:", len(regions))
print("Competition levels:", competition_levels)

Number of samples: 5000
Number of sectors: 10
Number of regions: 8
Competition levels: ['Low', 'Medium', 'High']

In [5]:
# Generate base opportunity information

opportunity_ids = [f"INV-{i:05d}" for i in range(1, N_SAMPLES + 1)]

selected_sectors = np.random.choice(sectors, size=N_SAMPLES)
selected_regions = np.random.choice(regions, size=N_SAMPLES)
selected_competition = np.random.choice(
    competition_levels,
    size=N_SAMPLES,
    p=[0.30, 0.50, 0.20]
)

opportunity_names = [
    f"{region} {sector} Opportunity"
    for region, sector in zip(selected_regions, selected_sectors)
]

df = pd.DataFrame({
    "opportunity_id": opportunity_ids,
    "opportunity_name": opportunity_names,
    "sector": selected_sectors,
    "region": selected_regions,
    "competition_level": selected_competition
})

df.head()

,opportunity_id,opportunity_name,sector,region,competition_level
0,INV-00001,Tabuk Technology Opportunity,Technology,Tabuk,Low
1,INV-00002,Asir Healthcare Opportunity,Healthcare,Asir,Medium
2,INV-00003,Eastern Province Education Opportunity,Education,Eastern Province,High
3,INV-00004,Madinah Logistics Opportunity,Logistics,Madinah,Medium
4,INV-00005,Qassim Technology Opportunity,Technology,Qassim,High

In [6]:
df.shape

(5000, 5)

In [7]:
# Generate financial features

# Investment size in million SAR
df["investment_size_million"] = np.round(
    np.random.lognormal(mean=5.2, sigma=1.0, size=N_SAMPLES),
    2
)

# Limit extreme values to keep data realistic
df["investment_size_million"] = df["investment_size_million"].clip(20, 5000)

# CAPEX usually represents a large part of investment size
df["capex_million"] = np.round(
    df["investment_size_million"] * np.random.uniform(0.55, 0.90, size=N_SAMPLES),
    2
)

# OPEX is annual operating cost
df["opex_million"] = np.round(
    df["investment_size_million"] * np.random.uniform(0.05, 0.25, size=N_SAMPLES),
    2
)

# Expected ROI varies by opportunity
df["expected_roi_percent"] = np.round(
    np.random.normal(loc=11, scale=6, size=N_SAMPLES),
    2
).clip(-5, 30)

# IRR is related to ROI but with some variation
df["irr_percent"] = np.round(
    df["expected_roi_percent"] + np.random.normal(loc=2, scale=4, size=N_SAMPLES),
    2
).clip(-5, 35)

# Payback period: lower is better
df["payback_period_years"] = np.round(
    np.random.normal(loc=7, scale=2.5, size=N_SAMPLES),
    2
).clip(1, 15)

# Revenue growth
df["revenue_growth_percent"] = np.round(
    np.random.normal(loc=8, scale=5, size=N_SAMPLES),
    2
).clip(-5, 25)

# Profit margin
df["profit_margin_percent"] = np.round(
    np.random.normal(loc=18, scale=9, size=N_SAMPLES),
    2
).clip(-10, 40)

# NPV depends partly on investment size and expected ROI
df["npv_million"] = np.round(
    (df["investment_size_million"] * (df["expected_roi_percent"] / 100) * np.random.uniform(2, 8, size=N_SAMPLES))
    - (df["investment_size_million"] * np.random.uniform(0.1, 0.5, size=N_SAMPLES)),
    2
).clip(-500, 3000)

df.head()

,opportunity_id,opportunity_name,sector,region,competition_level,investment_size_million,capex_million,opex_million,expected_roi_percent,irr_percent,payback_period_years,revenue_growth_percent,profit_margin_percent,npv_million
0,INV-00001,Tabuk Technology Opportunity,Technology,Tabuk,Low,163.15,91.34,22.63,14.29,17.19,11.70,6.75,8.15,37.19
1,INV-00002,Asir Healthcare Opportunity,Healthcare,Asir,Medium,67.46,47.73,11.44,19.08,20.73,5.18,7.90,40.00,49.05
2,INV-00003,Eastern Province Education Opportunity,Education,Eastern Province,High,213.29,165.94,12.03,8.38,7.92,6.69,8.79,19.71,20.20
3,INV-00004,Madinah Logistics Opportunity,Logistics,Madinah,Medium,23.72,19.82,3.41,16.41,18.17,3.30,11.64,28.78,26.97
4,INV-00005,Qassim Technology Opportunity,Technology,Qassim,High,131.04,84.34,21.33,9.21,9.21,5.91,12.61,21.53,68.98

In [8]:
df[
    [
        "investment_size_million",
        "expected_roi_percent",
        "irr_percent",
        "npv_million",
        "payback_period_years",
        "profit_margin_percent"
    ]
].describe()

,investment_size_million,expected_roi_percent,irr_percent,npv_million,payback_period_years,profit_margin_percent
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,296.998428,11.080380,13.031264,75.753434,7.011526,18.056412
std,371.472013,6.013142,7.201387,195.881220,2.471981,8.924205
min,20.000000,-5.000000,-5.000000,-500.000000,1.000000,-10.000000
25%,88.945000,6.947500,8.190000,-2.700000,5.320000,12.160000
50%,179.565000,11.080000,13.000000,26.310000,7.010000,18.215000
75%,351.635000,15.170000,17.932500,99.400000,8.640000,24.082500
max,4377.820000,30.000000,35.000000,3000.000000,15.000000,40.000000

In [9]:
# Generate market features

# Market size in billion SAR
df["market_size_billion"] = np.round(
    np.random.lognormal(mean=3.2, sigma=0.8, size=N_SAMPLES),
    2
).clip(1, 300)

# Market growth percentage
df["market_growth_percent"] = np.round(
    np.random.normal(loc=7, scale=5, size=N_SAMPLES),
    2
).clip(-3, 20)

# Demand score from 0 to 100
df["demand_score"] = np.round(
    np.random.normal(loc=65, scale=18, size=N_SAMPLES),
    2
).clip(0, 100)

# Customer adoption score from 0 to 100
df["customer_adoption_score"] = np.round(
    np.random.normal(loc=60, scale=20, size=N_SAMPLES),
    2
).clip(0, 100)

# Scalability score from 0 to 100
df["scalability_score"] = np.round(
    np.random.normal(loc=62, scale=19, size=N_SAMPLES),
    2
).clip(0, 100)

df.head()

,opportunity_id,opportunity_name,sector,region,competition_level,investment_size_million,capex_million,opex_million,expected_roi_percent,irr_percent,payback_period_years,revenue_growth_percent,profit_margin_percent,npv_million,market_size_billion,market_growth_percent,demand_score,customer_adoption_score,scalability_score
0,INV-00001,Tabuk Technology Opportunity,Technology,Tabuk,Low,163.15,91.34,22.63,14.29,17.19,11.70,6.75,8.15,37.19,9.97,3.06,81.65,69.31,68.94
1,INV-00002,Asir Healthcare Opportunity,Healthcare,Asir,Medium,67.46,47.73,11.44,19.08,20.73,5.18,7.90,40.00,49.05,15.38,1.28,23.04,79.19,91.22
2,INV-00003,Eastern Province Education Opportunity,Education,Eastern Province,High,213.29,165.94,12.03,8.38,7.92,6.69,8.79,19.71,20.20,11.90,9.34,86.52,60.60,86.64
3,INV-00004,Madinah Logistics Opportunity,Logistics,Madinah,Medium,23.72,19.82,3.41,16.41,18.17,3.30,11.64,28.78,26.97,9.28,14.04,65.22,22.05,65.52
4,INV-00005,Qassim Technology Opportunity,Technology,Qassim,High,131.04,84.34,21.33,9.21,9.21,5.91,12.61,21.53,68.98,31.57,8.13,58.12,70.88,42.25

In [10]:
df[
    [
        "market_size_billion",
        "market_growth_percent",
        "demand_score",
        "customer_adoption_score",
        "scalability_score"
    ]
].describe()

,market_size_billion,market_growth_percent,demand_score,customer_adoption_score,scalability_score
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,33.305068,6.963528,65.012756,59.753098,62.088974
std,30.692178,4.866946,17.477535,19.827269,18.466530
min,1.370000,-3.000000,0.000000,0.000000,0.000000
25%,14.277500,3.470000,53.090000,46.240000,49.702500
50%,24.190000,6.950000,64.870000,59.920000,62.300000
75%,41.112500,10.352500,77.520000,73.682500,75.022500
max,300.000000,20.000000,100.000000,100.000000,100.000000

In [11]:
# Generate risk features

# Base risk scores from 0 to 100
df["financial_risk_score"] = np.round(
    np.random.normal(loc=45, scale=20, size=N_SAMPLES),
    2
).clip(0, 100)

df["regulatory_risk_score"] = np.round(
    np.random.normal(loc=40, scale=22, size=N_SAMPLES),
    2
).clip(0, 100)

df["execution_risk_score"] = np.round(
    np.random.normal(loc=50, scale=20, size=N_SAMPLES),
    2
).clip(0, 100)

df["market_risk_score"] = np.round(
    np.random.normal(loc=43, scale=21, size=N_SAMPLES),
    2
).clip(0, 100)

df["dependency_risk_score"] = np.round(
    np.random.normal(loc=38, scale=22, size=N_SAMPLES),
    2
).clip(0, 100)

# Competition effect: high competition increases market risk slightly
competition_risk_adjustment = df["competition_level"].map({
    "Low": -5,
    "Medium": 0,
    "High": 8
})

df["market_risk_score"] = (
    df["market_risk_score"] + competition_risk_adjustment
).clip(0, 100)

# Overall risk score
df["overall_risk_score"] = np.round(
    df[
        [
            "financial_risk_score",
            "regulatory_risk_score",
            "execution_risk_score",
            "market_risk_score",
            "dependency_risk_score"
        ]
    ].mean(axis=1),
    2
)

df.head()

,opportunity_id,opportunity_name,sector,region,competition_level,investment_size_million,capex_million,opex_million,expected_roi_percent,irr_percent,...,market_growth_percent,demand_score,customer_adoption_score,scalability_score,financial_risk_score,regulatory_risk_score,execution_risk_score,market_risk_score,dependency_risk_score,overall_risk_score
0,INV-00001,Tabuk Technology Opportunity,Technology,Tabuk,Low,163.15,91.34,22.63,14.29,17.19,...,3.06,81.65,69.31,68.94,85.81,32.65,53.71,15.70,56.95,48.96
1,INV-00002,Asir Healthcare Opportunity,Healthcare,Asir,Medium,67.46,47.73,11.44,19.08,20.73,...,1.28,23.04,79.19,91.22,29.95,17.16,20.65,49.88,42.50,32.03
2,INV-00003,Eastern Province Education Opportunity,Education,Eastern Province,High,213.29,165.94,12.03,8.38,7.92,...,9.34,86.52,60.60,86.64,26.35,23.35,40.05,61.84,67.30,43.78
3,INV-00004,Madinah Logistics Opportunity,Logistics,Madinah,Medium,23.72,19.82,3.41,16.41,18.17,...,14.04,65.22,22.05,65.52,52.23,39.64,57.27,58.35,37.99,49.10
4,INV-00005,Qassim Technology Opportunity,Technology,Qassim,High,131.04,84.34,21.33,9.21,9.21,...,8.13,58.12,70.88,42.25,47.58,47.07,82.98,53.51,35.38,53.30

In [12]:
df[
    [
        "financial_risk_score",
        "regulatory_risk_score",
        "execution_risk_score",
        "market_risk_score",
        "dependency_risk_score",
        "overall_risk_score"
    ]
].describe()

,financial_risk_score,regulatory_risk_score,execution_risk_score,market_risk_score,dependency_risk_score,overall_risk_score
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,45.602482,39.814536,50.404220,42.928564,38.055294,43.360994
std,19.729822,21.267027,19.920833,20.783238,21.428844,9.269455
min,0.000000,0.000000,0.000000,0.000000,0.000000,11.220000
25%,32.072500,24.970000,37.137500,28.160000,22.915000,37.075000
50%,45.325000,39.430000,50.555000,42.535000,37.670000,43.290000
75%,59.152500,54.082500,63.815000,57.492500,52.410000,49.550000
max,100.000000,100.000000,100.000000,100.000000,100.000000,77.080000

In [13]:
# Generate strategic alignment features

# Scores from 0 to 100
df["vision_2030_alignment_score"] = np.round(
    np.random.normal(loc=68, scale=18, size=N_SAMPLES),
    2
).clip(0, 100)

df["economic_diversification_score"] = np.round(
    np.random.normal(loc=64, scale=19, size=N_SAMPLES),
    2
).clip(0, 100)

df["job_creation_score"] = np.round(
    np.random.normal(loc=58, scale=22, size=N_SAMPLES),
    2
).clip(0, 100)

df["localization_score"] = np.round(
    np.random.normal(loc=60, scale=20, size=N_SAMPLES),
    2
).clip(0, 100)

df["quality_of_life_score"] = np.round(
    np.random.normal(loc=62, scale=21, size=N_SAMPLES),
    2
).clip(0, 100)

# Sector-specific strategic boost
sector_strategic_boost = df["sector"].map({
    "Real Estate": 8,
    "Tourism": 10,
    "Entertainment": 8,
    "Healthcare": 9,
    "Logistics": 7,
    "Renewable Energy": 12,
    "Technology": 10,
    "Education": 8,
    "Retail": 3,
    "Infrastructure": 9
})

strategic_columns = [
    "vision_2030_alignment_score",
    "economic_diversification_score",
    "job_creation_score",
    "localization_score",
    "quality_of_life_score"
]

for col in strategic_columns:
    df[col] = (df[col] + sector_strategic_boost).clip(0, 100)

# Overall strategic impact score
df["strategic_impact_score"] = np.round(
    df[strategic_columns].mean(axis=1),
    2
)

df.head()

,opportunity_id,opportunity_name,sector,region,competition_level,investment_size_million,capex_million,opex_million,expected_roi_percent,irr_percent,...,execution_risk_score,market_risk_score,dependency_risk_score,overall_risk_score,vision_2030_alignment_score,economic_diversification_score,job_creation_score,localization_score,quality_of_life_score,strategic_impact_score
0,INV-00001,Tabuk Technology Opportunity,Technology,Tabuk,Low,163.15,91.34,22.63,14.29,17.19,...,53.71,15.70,56.95,48.96,76.84,68.45,100.00,68.27,92.31,81.17
1,INV-00002,Asir Healthcare Opportunity,Healthcare,Asir,Medium,67.46,47.73,11.44,19.08,20.73,...,20.65,49.88,42.50,32.03,82.05,100.00,84.51,96.38,91.63,90.91
2,INV-00003,Eastern Province Education Opportunity,Education,Eastern Province,High,213.29,165.94,12.03,8.38,7.92,...,40.05,61.84,67.30,43.78,58.19,96.47,54.80,71.68,22.05,60.64
3,INV-00004,Madinah Logistics Opportunity,Logistics,Madinah,Medium,23.72,19.82,3.41,16.41,18.17,...,57.27,58.35,37.99,49.10,85.49,80.36,68.48,56.42,54.87,69.12
4,INV-00005,Qassim Technology Opportunity,Technology,Qassim,High,131.04,84.34,21.33,9.21,9.21,...,82.98,53.51,35.38,53.30,70.13,57.04,100.00,94.91,50.99,74.61

In [14]:
df[
    [
        "vision_2030_alignment_score",
        "economic_diversification_score",
        "job_creation_score",
        "localization_score",
        "quality_of_life_score",
        "strategic_impact_score"
    ]
].describe()

,vision_2030_alignment_score,economic_diversification_score,job_creation_score,localization_score,quality_of_life_score,strategic_impact_score
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,75.348426,71.496368,65.595816,68.374352,69.573684,70.077782
std,16.776469,17.781209,20.737475,18.892273,19.840225,8.706744
min,7.000000,10.590000,3.000000,3.000000,3.000000,36.300000
25%,63.822500,59.437500,50.835000,55.880000,55.620000,64.210000
50%,76.310000,72.015000,65.740000,69.075000,70.400000,70.125000
75%,88.450000,84.817500,81.167500,82.122500,84.890000,76.192500
max,100.000000,100.000000,100.000000,100.000000,100.000000,97.050000

In [15]:
# Generate ESG / sustainability features

df["environmental_impact_score"] = np.round(
    np.random.normal(loc=58, scale=22, size=N_SAMPLES),
    2
).clip(0, 100)

df["social_impact_score"] = np.round(
    np.random.normal(loc=62, scale=20, size=N_SAMPLES),
    2
).clip(0, 100)

df["governance_score"] = np.round(
    np.random.normal(loc=66, scale=18, size=N_SAMPLES),
    2
).clip(0, 100)

# Sector-specific sustainability adjustment
sector_sustainability_boost = df["sector"].map({
    "Real Estate": 4,
    "Tourism": 5,
    "Entertainment": 3,
    "Healthcare": 6,
    "Logistics": 2,
    "Renewable Energy": 14,
    "Technology": 5,
    "Education": 6,
    "Retail": 1,
    "Infrastructure": 4
})

esg_columns = [
    "environmental_impact_score",
    "social_impact_score",
    "governance_score"
]

for col in esg_columns:
    df[col] = (df[col] + sector_sustainability_boost).clip(0, 100)

df["sustainability_score"] = np.round(
    df[esg_columns].mean(axis=1),
    2
)

df.head()

,opportunity_id,opportunity_name,sector,region,competition_level,investment_size_million,capex_million,opex_million,expected_roi_percent,irr_percent,...,vision_2030_alignment_score,economic_diversification_score,job_creation_score,localization_score,quality_of_life_score,strategic_impact_score,environmental_impact_score,social_impact_score,governance_score,sustainability_score
0,INV-00001,Tabuk Technology Opportunity,Technology,Tabuk,Low,163.15,91.34,22.63,14.29,17.19,...,76.84,68.45,100.00,68.27,92.31,81.17,95.59,53.23,83.81,77.54
1,INV-00002,Asir Healthcare Opportunity,Healthcare,Asir,Medium,67.46,47.73,11.44,19.08,20.73,...,82.05,100.00,84.51,96.38,91.63,90.91,91.58,65.18,64.37,73.71
2,INV-00003,Eastern Province Education Opportunity,Education,Eastern Province,High,213.29,165.94,12.03,8.38,7.92,...,58.19,96.47,54.80,71.68,22.05,60.64,84.57,18.88,54.31,52.59
3,INV-00004,Madinah Logistics Opportunity,Logistics,Madinah,Medium,23.72,19.82,3.41,16.41,18.17,...,85.49,80.36,68.48,56.42,54.87,69.12,19.74,54.31,70.71,48.25
4,INV-00005,Qassim Technology Opportunity,Technology,Qassim,High,131.04,84.34,21.33,9.21,9.21,...,70.13,57.04,100.00,94.91,50.99,74.61,100.00,54.64,63.07,72.57

In [16]:
df[
    [
        "environmental_impact_score",
        "social_impact_score",
        "governance_score",
        "sustainability_score"
    ]
].describe()

,environmental_impact_score,social_impact_score,governance_score,sustainability_score
count,5000.000000,5000.000000,5000.000000,5000.000000
mean,62.709624,67.253430,70.366074,66.776408
std,21.228650,19.255658,17.533523,11.378408
min,1.000000,1.060000,9.030000,24.280000
25%,47.910000,54.370000,58.467500,58.890000
50%,63.505000,67.860000,70.905000,67.145000
75%,78.055000,81.220000,82.940000,74.760000
max,100.000000,100.000000,100.000000,100.000000

In [17]:
# Feature engineering

# Risk-adjusted ROI:
# Higher ROI is good, but high risk should reduce attractiveness.
df["risk_adjusted_roi"] = np.round(
    df["expected_roi_percent"] / (df["overall_risk_score"] + 1),
    4
)

# Profitability index:
# Measures NPV relative to investment size.
df["profitability_index"] = np.round(
    df["npv_million"] / (df["investment_size_million"] + 1),
    4
)

# Payback efficiency:
# Higher ROI with shorter payback period is better.
df["payback_efficiency"] = np.round(
    df["expected_roi_percent"] / (df["payback_period_years"] + 1),
    4
)

# Market attractiveness:
# Combines market growth, demand, customer adoption, and scalability.
df["market_attractiveness_score"] = np.round(
    (
        (df["market_growth_percent"].clip(0, 20) / 20) * 25
        + (df["demand_score"] / 100) * 25
        + (df["customer_adoption_score"] / 100) * 25
        + (df["scalability_score"] / 100) * 25
    ),
    2
)

# Financial strength:
# Combines ROI, IRR, NPV, and profit margin into one normalized score.
df["financial_strength_score"] = np.round(
    (
        ((df["expected_roi_percent"] + 5) / 35) * 25
        + ((df["irr_percent"] + 5) / 40) * 25
        + ((df["npv_million"] + 500) / 3500) * 25
        + ((df["profit_margin_percent"] + 10) / 50) * 25
    ),
    2
).clip(0, 100)

df.head()

,opportunity_id,opportunity_name,sector,region,competition_level,investment_size_million,capex_million,opex_million,expected_roi_percent,irr_percent,...,strategic_impact_score,environmental_impact_score,social_impact_score,governance_score,sustainability_score,risk_adjusted_roi,profitability_index,payback_efficiency,market_attractiveness_score,financial_strength_score
0,INV-00001,Tabuk Technology Opportunity,Technology,Tabuk,Low,163.15,91.34,22.63,14.29,17.19,...,81.17,95.59,53.23,83.81,77.54,0.2860,0.2266,1.1252,58.80,40.56
1,INV-00002,Asir Healthcare Opportunity,Healthcare,Asir,Medium,67.46,47.73,11.44,19.08,20.73,...,90.91,91.58,65.18,64.37,73.71,0.5777,0.7165,3.0874,49.96,62.20
2,INV-00003,Eastern Province Education Opportunity,Education,Eastern Province,High,213.29,165.94,12.03,8.38,7.92,...,60.64,84.57,18.88,54.31,52.59,0.1871,0.0943,1.0897,70.11,36.20
3,INV-00004,Madinah Logistics Opportunity,Logistics,Madinah,Medium,23.72,19.82,3.41,16.41,18.17,...,69.12,19.74,54.31,70.71,48.25,0.3275,1.0910,3.8163,55.75,52.93
4,INV-00005,Qassim Technology Opportunity,Technology,Qassim,High,131.04,84.34,21.33,9.21,9.21,...,74.61,100.00,54.64,63.07,72.57,0.1696,0.5224,1.3329,52.97,38.86

In [18]:
df[
    [
        "risk_adjusted_roi",
        "profitability_index",
        "payback_efficiency",
        "market_attractiveness_score",
        "financial_strength_score"
    ]
].describe()

,risk_adjusted_roi,profitability_index,payback_efficiency,market_attractiveness_score,financial_strength_score
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,0.262835,0.257379,1.567990,55.595388,40.896224
std,0.160913,0.392058,1.172309,9.875924,10.141523
min,-0.227800,-0.763000,-2.155700,21.960000,6.660000
25%,0.155175,-0.026300,0.840475,48.837500,34.290000
50%,0.247250,0.209650,1.378950,55.480000,41.100000
75%,0.354825,0.497275,2.040650,62.452500,47.545000
max,1.174900,2.225400,13.875000,89.430000,75.540000

In [30]:
# Generate target variable: investment_score

# Competition penalty
competition_penalty = df["competition_level"].map({
    "Low": 4,
    "Medium": 0,
    "High": -6
})

# Payback score: shorter payback is better
payback_score = np.round(
    (1 - ((df["payback_period_years"] - 1) / 14)) * 100,
    2
).clip(0, 100)

# Risk score inverted: lower risk is better
risk_score_inverted = 100 - df["overall_risk_score"]

# Base investment score before calibration
base_score = (
    df["financial_strength_score"] * 0.32
    + df["market_attractiveness_score"] * 0.18
    + df["strategic_impact_score"] * 0.20
    + df["sustainability_score"] * 0.10
    + risk_score_inverted * 0.15
    + payback_score * 0.05
    + competition_penalty
)

# Add realistic noise so the target is not perfectly rule-based
noise = np.random.normal(loc=0, scale=2.5, size=N_SAMPLES)

raw_score = base_score + noise

# Calibrate score to use a wider 0–100 range
# This keeps relative ranking but improves score distribution.
lower_bound = np.percentile(raw_score, 2)
upper_bound = np.percentile(raw_score, 98)

calibrated_score = (
    (raw_score - lower_bound) / (upper_bound - lower_bound)
) * 100

df["investment_score"] = np.round(
    calibrated_score.clip(0, 100),
    2
)

# Convert score into recommendation
def assign_recommendation(score):
    if score >= 75:
        return "Invest"
    elif score >= 45:
        return "Review"
    else:
        return "Reject"

df["recommendation"] = df["investment_score"].apply(assign_recommendation)

df[
    [
        "investment_score",
        "recommendation",
        "financial_strength_score",
        "market_attractiveness_score",
        "strategic_impact_score",
        "sustainability_score",
        "overall_risk_score"
    ]
].head()

,investment_score,recommendation,financial_strength_score,market_attractiveness_score,strategic_impact_score,sustainability_score,overall_risk_score
0,80.10,Invest,40.56,58.80,81.17,77.54,48.96
1,90.23,Invest,62.20,49.96,90.91,73.71,32.03
2,22.60,Reject,36.20,70.11,60.64,52.59,43.78
3,76.81,Invest,52.93,55.75,69.12,48.25,49.10
4,32.86,Reject,38.86,52.97,74.61,72.57,53.30

In [31]:
df["investment_score"].describe()

count    5000.000000
mean       51.674290
std        23.761431
min         0.000000
25%        35.147500
50%        52.420000
75%        68.150000
max       100.000000
Name: investment_score, dtype: float64

In [32]:
df["recommendation"].value_counts()

recommendation
Review    2235
Reject    1920
Invest     845
Name: count, dtype: int64

In [33]:
# Final dataset check

print("Dataset shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nRecommendation distribution:")
print(df["recommendation"].value_counts())

df.head()

Dataset shape: (5000, 42)

Missing values:
0

Duplicate rows:
0

Recommendation distribution:
recommendation
Review    2235
Reject    1920
Invest     845
Name: count, dtype: int64

,opportunity_id,opportunity_name,sector,region,competition_level,investment_size_million,capex_million,opex_million,expected_roi_percent,irr_percent,...,social_impact_score,governance_score,sustainability_score,risk_adjusted_roi,profitability_index,payback_efficiency,market_attractiveness_score,financial_strength_score,investment_score,recommendation
0,INV-00001,Tabuk Technology Opportunity,Technology,Tabuk,Low,163.15,91.34,22.63,14.29,17.19,...,53.23,83.81,77.54,0.2860,0.2266,1.1252,58.80,40.56,80.10,Invest
1,INV-00002,Asir Healthcare Opportunity,Healthcare,Asir,Medium,67.46,47.73,11.44,19.08,20.73,...,65.18,64.37,73.71,0.5777,0.7165,3.0874,49.96,62.20,90.23,Invest
2,INV-00003,Eastern Province Education Opportunity,Education,Eastern Province,High,213.29,165.94,12.03,8.38,7.92,...,18.88,54.31,52.59,0.1871,0.0943,1.0897,70.11,36.20,22.60,Reject
3,INV-00004,Madinah Logistics Opportunity,Logistics,Madinah,Medium,23.72,19.82,3.41,16.41,18.17,...,54.31,70.71,48.25,0.3275,1.0910,3.8163,55.75,52.93,76.81,Invest
4,INV-00005,Qassim Technology Opportunity,Technology,Qassim,High,131.04,84.34,21.33,9.21,9.21,...,54.64,63.07,72.57,0.1696,0.5224,1.3329,52.97,38.86,32.86,Reject

In [34]:
# Save synthetic dataset

output_file = RAW_DATA_PATH / "synthetic_investment_opportunities.csv"

df.to_csv(output_file, index=False)

print(f"Dataset saved successfully to: {output_file}")

Dataset saved successfully to: d:\Senior last\ML\ai-investment-opportunity-analyzer\data\raw\synthetic_investment_opportunities.csv

In [35]:
# Confirm saved file exists

output_file.exists()

True

In [36]:
# Load saved dataset to verify

saved_df = pd.read_csv(output_file)

print("Saved dataset shape:", saved_df.shape)
saved_df.head()

Saved dataset shape: (5000, 42)

,opportunity_id,opportunity_name,sector,region,competition_level,investment_size_million,capex_million,opex_million,expected_roi_percent,irr_percent,...,social_impact_score,governance_score,sustainability_score,risk_adjusted_roi,profitability_index,payback_efficiency,market_attractiveness_score,financial_strength_score,investment_score,recommendation
0,INV-00001,Tabuk Technology Opportunity,Technology,Tabuk,Low,163.15,91.34,22.63,14.29,17.19,...,53.23,83.81,77.54,0.2860,0.2266,1.1252,58.80,40.56,80.10,Invest
1,INV-00002,Asir Healthcare Opportunity,Healthcare,Asir,Medium,67.46,47.73,11.44,19.08,20.73,...,65.18,64.37,73.71,0.5777,0.7165,3.0874,49.96,62.20,90.23,Invest
2,INV-00003,Eastern Province Education Opportunity,Education,Eastern Province,High,213.29,165.94,12.03,8.38,7.92,...,18.88,54.31,52.59,0.1871,0.0943,1.0897,70.11,36.20,22.60,Reject
3,INV-00004,Madinah Logistics Opportunity,Logistics,Madinah,Medium,23.72,19.82,3.41,16.41,18.17,...,54.31,70.71,48.25,0.3275,1.0910,3.8163,55.75,52.93,76.81,Invest
4,INV-00005,Qassim Technology Opportunity,Technology,Qassim,High,131.04,84.34,21.33,9.21,9.21,...,54.64,63.07,72.57,0.1696,0.5224,1.3329,52.97,38.86,32.86,Reject

In [37]:
saved_df["recommendation"].value_counts()

recommendation
Review    2235
Reject    1920
Invest     845
Name: count, dtype: int64